for config in $HOME/.shell/*.(zsh|sh); do
  source $config
done

autoload -U compinit && compinit
zmodload -i zsh/complist

HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000

export PATH=~/Library/Python/3.6/bin:$PATH

cd ~/code
