export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"

for config in $HOME/.shell/*.(zsh|sh); do
  source $config
done

autoload -U compinit && compinit
zmodload -i zsh/complist


export PATH=~/Library/Python/3.6/bin:$PATH
export PATH=~/Library/Python/2.7/bin:$PATH

cd ~/code
