let vimrcdir = '$HOME/.dotfiles/vim/'

" let g:python_host_prog = 'python'
" let g:python3_host_prog = 'python3'

" Use current repos virtualenv for ycm if it is found
exec ':source ' . vimrcdir . 'usercall.vim'
let git_dir = UserCall("gitdir")
if (!empty(git_dir) && filereadable(git_dir . '/.venv/bin/python'))
    let g:ycm_python_binary_path = (git_dir . '/.venv/bin/python')
else
    let g:ycm_python_binary_path = 'python'
endif

exec ':source ' . vimrcdir . 'colemak.vim'
exec ':source ' . vimrcdir . 'commands.vim'
exec ':source ' . vimrcdir . 'gitgutter.vim'
exec ':source ' . vimrcdir . 'indentation.vim'
exec ':source ' . vimrcdir . 'plugins.vim'

set t_Co=256
set number
set mouse=a
set tabstop=2
set shiftwidth=2
set expandtab
set foldmethod=syntax
set foldlevelstart=20
set foldlevel=0
set undofile
set undodir=~/.neovimundodir
set mmp=5000

" Show whitespace characters
set list

" makes webpack livereload work
set backupcopy=yes

" Hides current file when opening explorer
set hidden

syntax enable

hi Normal ctermbg=none

set backspace=start,eol,indent

set clipboard=unnamed

set omnifunc=syntaxcomplete#Complete

" colorscheme wells-colors

" To match base16 themes
"if filereadable(expand("~/.vimrc_background"))
"  let base16colorspace=256
"  source ~/.vimrc_background
"endif

" gruvbox
set termguicolors
set background=dark    " Setting dark mode
" set background=light   " Setting light mode

let g:gruvbox_contrast_light = 'medium'
autocmd vimenter * colorscheme gruvbox

" layout for all vim fzf windows
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6, 'relative': v:true } }

let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

