let vimrcdir = '$HOME/.vim/'
let g:python_host_prog = '$HOME/.config/py2_venv/bin/python'
let g:python3_host_prog = '$HOME/.config/py3_venv/bin/python'

" Use current repos virtualenv for ycm if it is found
exec ':source ' . vimrcdir . 'gitdir.vim'
let git_dir = GitDir()
if (!empty(git_dir) && filereadable(git_dir . '/.venv/bin/python'))
    let g:ycm_python_binary_path = (git_dir . '/.venv/bin/python')
else
    let g:ycm_python_binary_path = 'python'
endif

exec ':source ' . vimrcdir . 'colemak.vim'
exec ':source ' . vimrcdir . 'commands.vim'
exec ':source ' . vimrcdir . 'gitgutter.vim'
exec ':source ' . vimrcdir . 'indentation.vim'
exec ':source ' . vimrcdir . 'plugins.vim'

set t_Co=256
set number
set mouse=a
set tabstop=2
set shiftwidth=2
set expandtab

" Show whitespace characters
set list

" makes webpack livereload work
set backupcopy=yes

" Hides current file when opening explorer
set hidden

syntax enable

try
  colorscheme wells-colors
catch
  echo "Failed to load colorscheme"
endtry

hi Normal ctermbg=none

set backspace=start,eol,indent

set clipboard=unnamed

set omnifunc=syntaxcomplete#Complete
