alias ls='ls -GFh'
alias gs='git status'
alias gd='git diff'
alias gc='git checkout'
alias gl='git log'
alias glo='git log --name-only'
alias gls='git log --pretty=oneline --abbrev-commit'
alias glg='git log --graph --pretty=oneline --abbrev-commit --all'
alias gamend='git add --all; git commit --amend'
alias dev='cd ~/code'
alias vi='vim'
alias gt='go test -v ./...'
