export VISUAL='nvim'
export EDITOR="$VISUAL"
export GIT_EDITOR="$VISUAL"
alias vim="$VISUAL"

source "$HOME/.zsh/history.zsh"
source "$HOME/.zsh/aliases.zsh"
source "$HOME/.zsh/bindkey.zsh"
source "$HOME/.zsh/fzf.zsh"

# macos default less is built without the lesskey options, instead a brew
# version can be used. By default man uses /usr/bin/less.
export MANPAGER=$(which less)

# All non golang repos in ~/code
export CDPATH=.:$HOME/code

# Golang specific
export GOPATH=$HOME/code/go
export CDPATH=$CDPATH:$GOPATH/src/github.com:$GOPATH/src/golang.org:$GOPATH/src

# Python specific
export PIP_CACHE_DIR=$HOME/.cache/pip
# If we are running with pyenv, prepend PATH with pyenv shims (virtualenv.zsh
# depends on this, so source it after)
if command -v pyenv &> /dev/null; then export PATH="$(pyenv root)/shims:$PATH"; fi
source "$HOME/.zsh/virtualenv.zsh"
# YouCompleteMe requires dynamic python libaries
export PYTHON_CONFIGURE_OPTS="--enable-framework"

# base16 theme
BASE16_THEME=base16-summerfruit-dark
source "$HOME/.config/base16-shell/scripts/$BASE16_THEME.sh"

# promptinit - custom prompts, as customised below
autoload -Uz promptinit; promptinit
setopt promptsubst

function git_prompt() {
  local ref="$(git rev-parse --symbolic-full-name --abbrev-ref HEAD 2>/dev/null)"
  if [ -n "$ref" ]; then
    echo "(%{$fg_bold[magenta]%}${ref#refs/heads/}%{$reset_color%}) "
  fi
}

PROMPT='$(git_prompt)%{$fg_bold[green]%}${PWD/#$HOME/~}%{$reset_color%} $ '
RPROMPT=''

# zsh completion system
autoload -U compinit && compinit
zmodload -i zsh/complist

if [ -d "$HOME/code" ]
then
  cd ~/code
fi
