export VISUAL='nvim'
export EDITOR="$VISUAL"
export GIT_EDITOR="$VISUAL"
alias vim="$VISUAL"
export CODEDIR="$HOME/code"

# for gpg password caching
GPG_TTY=$(tty)
export GPG_TTY

source "$HOME/.zsh/functions.zsh"
source "$HOME/.zsh/history.zsh"
source "$HOME/.zsh/aliases.zsh"
source "$HOME/.zsh/bindkey.zsh"
source "$HOME/.zsh/fzf.zsh"

if [ -f $HOME/.selfrc/selfrc.zsh ];
then
  source "$HOME/.selfrc/selfrc.zsh"
fi

# macos default less is built without the lesskey options, instead a brew
# version can be used. By default man uses /usr/bin/less.
export MANPAGER=$(which less)

# Golang specific
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export PATH=$PATH:$GOBIN

# Python specific
export PIP_CACHE_DIR=$HOME/.cache/pip

# YouCompleteMe requires dynamic python libaries
#export PYTHON_CONFIGURE_OPTS="--enable-framework"

# base16 theme hardcode
BASE16_THEME=base16-summerfruit-dark
source "$HOME/.config/base16-shell/scripts/$BASE16_THEME.sh"

# allow easy base16 switching
#BASE16_SHELL="$HOME/.config/base16-shell/"
#[ -n "$PS1" ] && \
#    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
#        eval "$("$BASE16_SHELL/profile_helper.sh")"

# promptinit - custom prompts, as customised below
autoload -Uz promptinit; promptinit
setopt promptsubst

function git_prompt() {
  local ref="$(git rev-parse --symbolic-full-name --abbrev-ref HEAD 2>/dev/null)"
  if [ -n "$ref" ]; then
    echo "(%{$fg_bold[magenta]%}${ref#refs/heads/}%{$reset_color%}) "
  fi
}

PROMPT='$(git_prompt)%{$fg_bold[green]%}${PWD/#$HOME/~}%{$reset_color%} $ '
RPROMPT=''

# zsh completion system
autoload -U compinit && compinit
zmodload -i zsh/complist

if [ -d $CODEDIR ]
then
  cd $CODEDIR
fi
